const MapEditor = (() => {
 let map=OTT.base('Bản đồ tự tạo'), tool='obstacle'; const $=id=>document.getElementById(id);
 function render(){let b=$('editorBoard');b.style.setProperty('--cols',map.cols);b.style.setProperty('--rows',map.rows);b.innerHTML='';for(let r=0;r<map.rows;r++)for(let c=0;c<map.cols;c++){let cell=document.createElement('button');cell.className='cell';let obs=map.obstacles.some(x=>x.r===r&&x.c===c), p=OTT.at(map,r,c);if(obs){cell.classList.add('obstacle');cell.textContent='◆'}if(map.bases[1].r===r&&map.bases[1].c===c)cell.classList.add('base1');if(map.bases[2].r===r&&map.bases[2].c===c)cell.classList.add('base2');if(p){cell.append(piece(p))}cell.onclick=()=>paint(r,c);b.append(cell)}}
 function piece(p){let x=document.createElement('i');x.className='piece p'+p.player;x.textContent=OTT.types[p.type].icon;return x}
 function paint(r,c){map.pieces=map.pieces.filter(p=>p.r!==r||p.c!==c);map.obstacles=map.obstacles.filter(x=>x.r!==r||x.c!==c);if(tool==='base1'||tool==='base2'){map.bases[tool==='base1'?1:2]={r,c}}else if(tool==='obstacle')map.obstacles.push({r,c});else if(tool!=='erase'){let [pl,type]=tool.split('-');map.pieces.push({id:Date.now()+Math.random(),player:pl==='p1'?1:2,type,r,c})}render()}
 function resize(){let rows=+$('editorRows').value,cols=+$('editorCols').value;map=OTT.base('Bản đồ tự tạo',rows,cols);render()}
 function init(play){document.querySelectorAll('[data-tool]').forEach(x=>x.onclick=()=>{tool=x.dataset.tool;document.querySelectorAll('[data-tool]').forEach(q=>q.classList.toggle('active',q===x))});document.querySelector('[data-tool="obstacle"]').classList.add('active');$('resizeEditor').onclick=resize;$('clearMap').onclick=()=>{map=OTT.base('Bản đồ tự tạo',map.rows,map.cols);map.pieces=[];render()};$('randomizeMap').onclick=()=>{map=OTT.randomMap();$('editorRows').value=map.rows;$('editorCols').value=map.cols;render()};$('exportMap').onclick=()=>{localStorage.setItem('ottv2-custom-map',JSON.stringify(map));$('editorStatus').textContent='Đã lưu vào Local Storage ✓'};$('playEditorMap').onclick=()=>play(OTT.clone(map));let saved=localStorage.getItem('ottv2-custom-map');if(saved)map=JSON.parse(saved);render()}
 return {init,get:()=>OTT.clone(map),render};
})();
