(() => {
  // Defensive DOM helper: a conditional class must never pass an empty token.
  const nativeAddClass = DOMTokenList.prototype.add;
  DOMTokenList.prototype.add = function (...tokens) {
    return nativeAddClass.apply(this, tokens.filter(Boolean));
  };
  const $=id=>document.getElementById(id); let chosen,game,initialMap,selected,timerId,seconds=30,sound=true,timed=true;
  const modes=[['classic','⚔','Cổ điển','Bàn 9×9 chuẩn.'],['tactical','⛰','Chiến địa hiểm trở','Ba map chướng ngại.'],['random','⚄','Chiến trường hỗn loạn','Map ngẫu nhiên cân bằng.'],['custom','✎','Bản đồ tự tạo','Map từ Editor.']];
  const other=p=>p===1?2:1;
  function nav(n){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${n}`));if(n!=='game')stopTimer();if(n==='select')renderSelect();if(n==='editor')MapEditor.render();document.querySelector('.modal').classList.remove('show')}
  function beep(f=440){if(!sound)return;const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}
  function renderSelect(){const c=$('modeCards');c.innerHTML=modes.map(x=>`<article class="mode-card ${chosen?.mode===x[0]?'selected':''}" data-mode="${x[0]}"><div class="icon">${x[1]}</div><h3>${x[2]}</h3><p>${x[3]}</p></article>`).join('');c.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{chosen={mode:x.dataset.mode};renderSelect()});const ch=$('mapChoices');ch.innerHTML='';if(chosen?.mode==='tactical')Object.keys({chokepoint:1,maze:1,island:1}).forEach(k=>{const b=document.createElement('button');b.className=`map-choice ${chosen.map===k?'selected':''}`;b.textContent=OTT.maps[k]().name;b.onclick=()=>{chosen.map=k;renderSelect()};ch.append(b)});const ok=chosen&&(chosen.mode!=='tactical'||chosen.map)&&(chosen.mode!=='custom'||localStorage.getItem('ottv2-custom-map'));$('startMatch').disabled=!ok;$('startMatch').textContent=ok?'▶ Bắt đầu trận đấu':'Chọn chế độ để bắt đầu'}
  function createMap(){if(chosen.mode==='classic')return OTT.maps.classic();if(chosen.mode==='tactical')return OTT.maps[chosen.map]();if(chosen.mode==='random')return OTT.randomMap();return JSON.parse(localStorage.getItem('ottv2-custom-map'))}
  function start(map){if(!map?.pieces?.some(p=>p.player===1)||!map?.pieces?.some(p=>p.player===2)){alert('Map cần có quân của cả P1 và P2.');return}initialMap=OTT.clone(map);game={map:OTT.clone(map),player:1,log:[],started:{1:{},2:{}}};[1,2].forEach(p=>Object.keys(OTT.types).forEach(t=>game.started[p][t]=game.map.pieces.some(x=>x.player===p&&x.type===t)));selected=null;nav('game');$('mapTitle').textContent=game.map.name;renderGame();startTimer()}
  function tile(r,c){const m=game.map,cell=document.createElement('button'),p=OTT.at(m,r,c),active=selected&&m.pieces.find(x=>x.id===selected),move=active&&OTT.validMoves(m,active).find(x=>x.r===r&&x.c===c);cell.type='button';cell.className='cell';cell.style.gridRow=String(r+1);cell.style.gridColumn=String(c+1);if(m.obstacles.some(x=>x.r===r&&x.c===c)){cell.classList.add('obstacle');cell.textContent='◆'}if(m.bases[1].r===r&&m.bases[1].c===c)cell.classList.add('base1');if(m.bases[2].r===r&&m.bases[2].c===c)cell.classList.add('base2');if(active?.r===r&&active?.c===c)cell.classList.add('selected');if(move)cell.classList.add('valid',move.attack?'attack':'');if(p){const icon=document.createElement('i');icon.className=`piece p${p.player}`;icon.textContent=OTT.types[p.type].icon;cell.append(icon)}cell.onclick=()=>clickCell(r,c);return cell}
  function renderGame(){const m=game.map,b=$('gameBoard');b.replaceChildren();b.style.gridTemplateColumns=`repeat(${m.cols}, minmax(0, 1fr))`;b.style.gridTemplateRows=`repeat(${m.rows}, minmax(0, 1fr))`;b.style.aspectRatio=`${m.cols} / ${m.rows}`;for(let r=0;r<m.rows;r++)for(let c=0;c<m.cols;c++)b.append(tile(r,c));const t=$('turnPill');t.className=`turn-pill p${game.player}`;t.textContent=`P${game.player} ${game.player===1?'Đỏ':'Xanh'} đi lượt này`;$('inventory').innerHTML=[1,2].map(p=>Object.entries(OTT.types).map(([k,v])=>`<div class="inv">P${p} ${v.icon}<b>${m.pieces.filter(x=>x.player===p&&x.type===k).length}</b></div>`).join('')).join('');$('moveLog').innerHTML=game.log.slice(-9).reverse().map(x=>`<li>${x}</li>`).join('')}
  function clickCell(r,c){const m=game.map,p=OTT.at(m,r,c),a=selected&&m.pieces.find(x=>x.id===selected),dest=a&&OTT.validMoves(m,a).some(x=>x.r===r&&x.c===c);if(dest){performMove(a,r,c);return}if(p?.player===game.player){selected=p.id;$('hint').textContent=`Đã chọn ${OTT.types[p.type].name}. Xanh: di chuyển; đỏ: giao tranh.`;renderGame();beep()}else if(selected){selected=null;$('hint').textContent='Ô này không hợp lệ.';renderGame()}}
  function performMove(p,r,c){const m=game.map,enemy=OTT.at(m,r,c),player=game.player;let log=`P${player}: ${OTT.types[p.type].name} → hàng ${r+1}, cột ${c+1}`;if(enemy){if(OTT.winner(p,enemy)==='attacker'){m.pieces=m.pieces.filter(x=>x.id!==enemy.id);p.r=r;p.c=c;log+=' (ăn quân)';beep(750)}else{m.pieces=m.pieces.filter(x=>x.id!==p.id);log+=' (thua giao tranh)';beep(160)}}else{p.r=r;p.c=c;beep(500)}game.log.push(log);selected=null;const foe=other(player),onTarget=OTT.at(m,r,c),base=m.bases[foe];let reason=onTarget?.player===player&&base.r===r&&base.c===c?'đã chiếm căn cứ đối thủ.':'';for(const type of Object.keys(OTT.types))if(game.started[foe][type]&&!m.pieces.some(x=>x.player===foe&&x.type===type))reason=`đã loại toàn bộ quân ${OTT.types[type].name} của đối thủ.`;if(reason){renderGame();finish(player,reason);return}game.player=foe;seconds=30;$('hint').textContent=`Đến lượt P${foe}.`;renderGame()}
  function startTimer(){stopTimer();seconds=30;$('timer').textContent=seconds;if(!timed)return;timerId=setInterval(()=>{seconds--;if(seconds>0){$('timer').textContent=seconds;return}selected=null;game.log.push(`P${game.player} hết giờ.`);game.player=other(game.player);seconds=30;renderGame();beep(180)},1000)}function stopTimer(){clearInterval(timerId)}
  function finish(p,why){stopTimer();$('victoryTitle').textContent=`P${p} ${p===1?'Đỏ':'Xanh'} chiến thắng!`;$('victoryReason').textContent=`P${p} thắng vì ${why}`;document.querySelector('.modal').classList.add('show')}
  document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>nav(x.dataset.nav));$('startMatch').onclick=()=>start(createMap());$('restartGame').onclick=()=>start(initialMap);$('playAgain').onclick=()=>start(initialMap);$('surrenderGame').onclick=()=>finish(other(game.player),`P${game.player} đã đầu hàng.`);$('soundToggle').onchange=e=>sound=e.target.checked;$('timerToggle').onchange=e=>timed=e.target.checked;MapEditor.init(start);renderSelect();
})();
